//! What each installer family needs on the wire, in one place.
//!
//! **Proxmox is the founding case and the odd one out.** Every other family takes a
//! `GET` plus kernel arguments; Proxmox alone wants the answer's *location* carried
//! inside the image, and then POSTs a body to it. A design that only works for the POST
//! path would be wrong by default, so the table below states each family's needs
//! side by side rather than generalising from the one we met first.
//!
//! The exact spellings are per-family, versioned, and precisely the sort of thing that
//! gets half-remembered. They live here, they are tested per family, and they are
//! nowhere else in the codebase.
//!
//! Two properties of iPXE's own parser shape what may be written here, and both were
//! read out of its source rather than remembered:
//!
//! - **`;` separates commands only as a whole whitespace-delimited token.**
//!   `split_command` in `core/exec.c` splits on whitespace and the separator is
//!   recognised by `strcmp(token, ";")`, so `ds=nocloud-net;s=http://…` is one argument
//!   and needs no escaping. Writing `foo ; bar` would be two commands.
//! - **A trailing `\` continues a line**, which is how a kernel command line longer
//!   than a terminal stays readable.
//!
//! What this module produces is an ordinary `.ipxe` **answer document**. It is printed,
//! never installed: saved into the answers directory it goes through the existing
//! selection, layering and templating unchanged. The server does not become clever
//! about booting — it gains a generator, and the composition engine it already has does
//! the rest.

use super::catalog::Entry;
use super::probe::Family;

/// The two listeners, as a client must be able to reach them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Endpoints {
    /// Where images, kernels and initrds come from.
    pub media: String,
    /// Where answers come from.
    pub answer: String,
}

/// Write the `.ipxe` answer document that boots one catalogue entry.
pub fn ipxe(entry: &Entry, endpoints: &Endpoints) -> Result<String, String> {
    let family = entry.family();
    if !entry.bootable() {
        return Err(format!(
            "{}: no kernel and initrd were found in it{}. It can still be served whole — \
             `sanboot` it, or write it to a stick — but there is no stanza to generate.",
            entry.id,
            match family {
                Family::Unknown => ", and no probe row claims it",
                _ => "",
            }
        ));
    }

    let media = endpoints.media.trim_end_matches('/');
    let answer = endpoints.answer.trim_end_matches('/');
    let id = &entry.id;
    let kernel = format!("{media}/{id}/kernel");
    let initrd = format!("{media}/{id}/initrd");
    let image = format!("{media}/{id}/iso");

    // `{{ mac }}` is filled by the answer engine's own templating, from the facts the
    // request carries. A missing fact is an error there, never an empty string — which
    // is what stops a machine installing itself against a truncated URL.
    let mut out = String::from("#!ipxe\n");
    out.push_str(&format!(
        "# {} — generated by `rescriptum media ipxe {id}`.\n\
         # An ordinary answer document: selection, layering and templating all apply.\n",
        entry.describe()
    ));

    match family {
        // Upstream's own output, character for character. `--pxe-loader ipxe` writes
        // `kernel vmlinuz ramdisk_size=16777216 rw quiet initrd=initrd.img` plus the
        // chosen option's parameters, then `initrd initrd.img`, `initrd <iso>
        // proxmox.iso`, `boot`. **`proxmox-start-auto-installer` is the parameter that
        // selects the automated path**; without it the machine boots the interactive
        // installer and waits for a human who is not coming.
        Family::Proxmox => {
            out.push_str(&format!(
                "kernel {kernel} ramdisk_size=16777216 rw quiet initrd=initrd.img \\\n\
                 \x20   splash=silent proxmox-start-auto-installer\n"
            ));
            // The second argument renames the downloaded file inside the initramfs, so
            // it matches the `initrd=` above; without it the name would come from the
            // URL and the kernel would not find it.
            out.push_str(&format!("initrd {initrd} initrd.img\n"));
            // The ISO travels as a second initrd, and the installer reads
            // `/cdrom/auto-installer-mode.toml` from it. That file is what carries the
            // answer URL — nothing on this command line does.
            out.push_str(&format!("initrd {image} proxmox.iso\n"));
        }
        Family::Debian => {
            out.push_str(&format!(
                "kernel {kernel} auto=true priority=critical \\\n\
                 \x20   preseed/url={answer}/debian?mac={{{{ mac }}}}\n"
            ));
            out.push_str(&format!("initrd {initrd}\n"));
        }
        // The one shape that is not a single URL: cloud-init's NoCloud datasource
        // fetches `user-data` *and* `meta-data` from a prefix. `facts.rs` labels a
        // request's `path`, `file` and `segment`, so one answer set can tell the two
        // apart with a selector — which is also why `seed` is not an endpoint alias.
        Family::Ubuntu => {
            out.push_str(&format!(
                "kernel {kernel} autoinstall \\\n\
                 \x20   ds=nocloud-net;s={answer}/ubuntu/{{{{ mac }}}}/ \\\n\
                 \x20   url={image} initrd=initrd\n"
            ));
            out.push_str(&format!("initrd {initrd} initrd\n"));
        }
        Family::Rhel => {
            out.push_str(&format!(
                "kernel {kernel} inst.ks={answer}/rhel?mac={{{{ mac }}}} \\\n\
                 \x20   inst.stage2={image}\n"
            ));
            out.push_str(&format!("initrd {initrd}\n"));
        }
        Family::Suse => {
            out.push_str(&format!(
                "kernel {kernel} autoyast={answer}/suse?mac={{{{ mac }}}} \\\n\
                 \x20   install={image}\n"
            ));
            out.push_str(&format!("initrd {initrd}\n"));
        }
        Family::CoreOs => {
            // The live rootfs is a file inside the image, served by path rather than
            // extracted — the same seek the kernel and initrd routes use.
            out.push_str(&format!(
                "kernel {kernel} ignition.config.url={answer}/coreos?mac={{{{ mac }}}} \\\n\
                 \x20   coreos.live.rootfs_url={media}/{id}/file/images/pxeboot/rootfs.img\n"
            ));
            out.push_str(&format!("initrd {initrd}\n"));
        }
        Family::Unknown => unreachable!("an unplaced image is not bootable"),
    }

    out.push_str("boot\n");
    Ok(out)
}

/// How the answer this stanza points at will be reached, for `media ipxe` to print
/// beside the script and for the guide to quote. Nothing generates the answer itself:
/// that is the operator's document, and this is only where to put it.
pub fn where_the_answer_goes(family: Family) -> &'static str {
    match family {
        Family::Proxmox => {
            "The image must carry `/auto-installer-mode.toml` naming the answer URL — \
             `proxmox-auto-install-assistant prepare-iso --fetch-from http --url …` \
             writes it. Nothing on the kernel command line carries it."
        }
        Family::Debian => "Save a `.preseed` answer; it is fetched from /debian.",
        Family::Ubuntu => {
            "Save `.yaml` answers reached as /ubuntu/<mac>/user-data and \
             /ubuntu/<mac>/meta-data — cloud-init fetches both, so a selector on the \
             `file` label tells them apart."
        }
        Family::Rhel => "Save a `.ks` answer; it is fetched from /rhel.",
        Family::Suse => "Save an `.autoyast` answer; it is fetched from /suse.",
        Family::CoreOs => "Save an `.ign` answer; it is fetched from /coreos.",
        Family::Unknown => "Nothing here knows how this image boots.",
    }
}

#[cfg(test)]
mod tests {
    use super::super::probe::{Arch, Probed};
    use super::*;
    use std::path::PathBuf;

    fn entry(family: Option<Family>, kernel: Option<&str>) -> Entry {
        Entry {
            id: "img".to_string(),
            path: PathBuf::from("/srv/media/img.iso"),
            size: 1024,
            digest: None,
            probed: Probed {
                family,
                version: Some("Test Image 1.0".to_string()),
                arch: Some(Arch::X86_64),
                kernel: kernel.map(str::to_string),
                initrd: kernel.map(|_| "/initrd".to_string()),
                external: false,
                zstd_initrd: false,
            },
            beside: None,
            prepared: None,
        }
    }

    fn endpoints() -> Endpoints {
        Endpoints {
            media: "http://192.0.2.10:8001".to_string(),
            answer: "http://192.0.2.10:8000".to_string(),
        }
    }

    fn render(family: Family) -> String {
        ipxe(&entry(Some(family), Some("/kernel")), &endpoints()).expect("renders")
    }

    /// **A stanza proven for one family claims six.** Each is asserted on the argument
    /// that actually starts its unattended install, per the plan's own rule that the
    /// founding case must not become the template.
    #[test]
    fn every_family_gets_the_argument_that_starts_its_install() {
        let cases: &[(Family, &str)] = &[
            // Not a URL: the parameter that selects the automated path. Without it a
            // Proxmox machine boots the interactive installer and waits forever.
            (Family::Proxmox, "proxmox-start-auto-installer"),
            (Family::Debian, "preseed/url=http://192.0.2.10:8000/debian"),
            (
                Family::Ubuntu,
                "ds=nocloud-net;s=http://192.0.2.10:8000/ubuntu/",
            ),
            (Family::Rhel, "inst.ks=http://192.0.2.10:8000/rhel"),
            (Family::Suse, "autoyast=http://192.0.2.10:8000/suse"),
            (
                Family::CoreOs,
                "ignition.config.url=http://192.0.2.10:8000/coreos",
            ),
        ];
        for (family, needle) in cases {
            let script = render(*family);
            assert!(script.contains(needle), "{}: {script}", family.label());
        }
    }

    #[test]
    fn every_family_loads_a_kernel_an_initrd_and_boots() {
        for family in [
            Family::Proxmox,
            Family::Debian,
            Family::Ubuntu,
            Family::Rhel,
            Family::Suse,
            Family::CoreOs,
        ] {
            let script = render(family);
            assert!(script.starts_with("#!ipxe\n"), "{}", family.label());
            assert!(
                script.contains("kernel http://192.0.2.10:8001/img/kernel"),
                "{}",
                family.label()
            );
            assert!(
                script.contains("initrd http://192.0.2.10:8001/img/initrd"),
                "{}",
                family.label()
            );
            assert!(script.ends_with("boot\n"), "{}", family.label());
        }
    }

    #[test]
    fn the_proxmox_stanza_matches_what_the_assistant_itself_emits() {
        // `--pxe-loader ipxe` is upstream's own statement of this stanza, and it is the
        // reference this must not drift from: the kernel parameters, the initrd renamed
        // to match `initrd=`, and the ISO carried as a second initrd named proxmox.iso.
        let script = render(Family::Proxmox);
        assert!(script.contains("ramdisk_size=16777216 rw quiet initrd=initrd.img"));
        assert!(script.contains("splash=silent proxmox-start-auto-installer"));
        assert!(script.contains("initrd http://192.0.2.10:8001/img/initrd initrd.img"));
        assert!(script.contains("initrd http://192.0.2.10:8001/img/iso proxmox.iso"));
        // And nothing on the command line names the answer: it rides inside the image.
        assert!(!script.contains("8000"), "{script}");
    }

    #[test]
    fn a_semicolon_inside_an_argument_is_left_alone() {
        // iPXE's `split_command` splits on whitespace and recognises the separator by
        // `strcmp(token, ";")`, so `ds=nocloud-net;s=…` is one argument. Escaping it
        // would corrupt the value cloud-init receives; splitting it would run `s=…` as
        // a command. Neither happens, and this pins that.
        let script = render(Family::Ubuntu);
        assert!(script.contains("ds=nocloud-net;s="), "{script}");
        assert!(!script.contains("\\;"), "no escaping: {script}");
        for line in script.lines() {
            assert!(
                !line.split_whitespace().any(|token| token == ";"),
                "a bare `;` token would split this line into two commands: {line}"
            );
        }
    }

    #[test]
    fn the_templated_mac_survives_into_the_answer_url() {
        // The document is a template the answer engine fills per request, which is what
        // lets one stanza cover a rack. A missing fact is an error there, so a truncated
        // URL never reaches a machine.
        let script = render(Family::Debian);
        assert!(script.contains("?mac={{ mac }}"), "{script}");
    }

    #[test]
    fn an_image_no_probe_placed_is_refused_with_a_reason() {
        // Refusing is a complete answer: the image is still servable whole.
        let e = ipxe(&entry(None, None), &endpoints()).expect_err("must refuse");
        assert!(e.contains("no probe row claims it"), "{e}");
        assert!(e.contains("sanboot"), "{e}");
    }

    #[test]
    fn a_trailing_slash_on_an_endpoint_does_not_double_up() {
        let script = ipxe(
            &entry(Some(Family::Rhel), Some("/kernel")),
            &Endpoints {
                media: "http://192.0.2.10:8001/".to_string(),
                answer: "http://192.0.2.10:8000/".to_string(),
            },
        )
        .expect("renders");
        assert!(!script.contains("//img"), "{script}");
        assert!(!script.contains("8000//"), "{script}");
    }
}
